//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Micronet_User.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Register
    {
        public int User_ID { get; set; }

        [Required(ErrorMessage ="Name Is Required")]
        public string Name { get; set; }
        [Required(ErrorMessage ="Email is Required")]
       
        public string Email { get; set; }

        [Required(ErrorMessage ="Password is required")]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        [StringLength(20,MinimumLength =6, ErrorMessage = "Password should have atleast 6 characters")]
        public string Password { get; set; }
    }
}
